packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^26
  "@vitest/browser-playwright": ^4
  "@vitest/coverage-v8": ^4
  typescript: ^7
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
  vitest: ^4
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  better-sqlite3: true
  esbuild: true
  msw: true
